### ISSUE TITLE
App doesn't start from the icon

### ISSUE THREAD

**Issue by julianfairfax** [flathub/ch.protonmail.protonmail-import-export-app#24]
The desktop file contains this line: `/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=protonmail-import-export-app ch.protonmail.protonmail-import-export-app`, which when running in the terminal, outputs this: `bwrap: execvp protonmail-import-export-app: No such file or directory`. The app can be opened with `/usr/bin/flatpak run --branch=stable --arch=x86_64 ch.protonmail.protonmail-import-export-app`. This should be made the default in the desktop file.

**Comment by A6GibKm** [comment]
https://github.com/flathub/ch.protonmail.protonmail-import-export-app/pull/25 looks correct but please report back if it actually fixed the issue.
