### ISSUE TITLE
The app don't start on KDE Neon

### ISSUE THREAD

**Issue by VosaXalo** [flathub/ch.protonmail.protonmail-import-export-app#9]
I'm on KDE Neon 20.04 with Wayland session and Plasma 5.22.2.
When I run the app in a terminal the following error message shows up:
```
➤ /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=protonmail-import-export-app ch.protonmail.protonmail-import-export-app
bwrap: execvp protonmail-import-export-app: No such file or directory
```

**Comment by A6GibKm** [comment]
I cannot reproduce this, are you sure you are on the latest version of the app?

**Comment by VosaXalo** [comment]
Hi @A6GibKm 
yes, I have installed the latest version 1.3.3-1.
I have also tried to remove completely the app with the following command:

> `flatpak uninstall --delete-data  ch.protonmail.protonmail-import-export-app `

and then I have installed it again, but the error message is always the same:

> ➤ /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=protonmail-import-export-app ch.protonmail.protonmail-import-export-app
> **bwrap: execvp protonmail-import-export-app: No such file or directory**

I can add that it's only since a couple of versions that I have this issue. Before I have already used the app with success.

**Comment by VosaXalo** [comment]
My flatpak version is: 1.11.2

I entered the sandbox and run /app/bin/proton-ie. The app starts correctly and in the terminal the following message shows up:

> [📦 ch.protonmail.protonmail-import-export-app bin]$ proton-ie 
> time="Jun 29 13:34:43.667" level=error msg="Could not authorize and unlock user" error="failed to refresh API auth: Invalid refresh token" pkg=users user="bfDr86xmLwxGgLU8ur44GLm4aS1t0r7F7bmxahYHk0rMibl0gyQC4o0YODrpQOdBn0fTJt8acwty_r_-0rFBWQ=="

I have tried to run /app/lib/protonmail/import-export/proton-ie

> [📦 ch.protonmail.protonmail-import-export-app import-export]$ proton-ie

and the app starts correctly without any messages.

I have tried also to run /app/lib/protonmail/import-export/proton-ie-launcher

> [📦 ch.protonmail.protonmail-import-export-app import-export]$ ./proton-ie-launcher

and the app starts correctly without any messages.

It's only with the "normal" command that the app won't start. I agree: this is really weird.
